services:
# ----- Cron tasks -----
    phpbb.mediaembed.cron.task.mediaembed:
        class: phpbb\mediaembed\cron\mediaembed
        arguments:
            - '@config'
            - '@cache.driver'
        calls:
            - [set_name, [cron.task.mediaembed]]
        tags:
            - { name: cron.task }
