imports:
    - { resource: cron.yml }

services:
    phpbb.mediaembed.listener:
        class: phpbb\mediaembed\event\main_listener
        arguments:
            - '@auth'
            - '@config'
            - '@config_text'
            - '@language'
            - '@template'
            - '@phpbb.mediaembed.customsitescollection'
            - '%core.cache_dir%'
        tags:
            - { name: event.listener }

    phpbb.mediaembed.customsitescollection:
        class: phpbb\mediaembed\collection\customsitescollection
        arguments:
            - '@ext.manager'
